---
- name: Cisco Switch port config
  connection: network_cli
  gather_facts:
  hosts: Cisco_Switches

  tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_lag_interfaces:
        config:
        - name: Port-channel10
          members:
          - member: GigabitEthernet0/10
            mode: auto
          - member: GigabitEthernet0/11
            mode: auto
        - name: Port-channel20
          members:
          - member: GigabitEthernet0/12
            mode: on
        - name: Port-channel30
          members:
          - member: GigabitEthernet0/13
            mode: active
        state: merged

    
