---
- name:  facts
  connection: network_cli
  gather_facts: false
  hosts: Cisco_Switches

  tasks:
    - name: Accespt ansible net hostname
      ios_facts:
        gather_subset: all

    - name: Get current date
      local_action: command date +%Y-%b-%d
      register: date

    - name: Get current time
      local_action: command date +%H:%M
      register: time

    - name: Get running-config and save it
      cisco.ios.config:
        backup: true
        backup_options:
          dir_path: /backup/Cisco_Switches/{{ date.stdout }}_at_{{ time.stdout }}
          filename: "{{ ansible_net_hostname }}_{{ ansible_host }}.cfg"
          
