---
- name: Cisco Switch port config
  connection: network_cli
  gather_facts:
  hosts: Cisco_Switches

  tasks: 
    - name: Merge module attributes of given access-groups
      cisco.ios.ios_acl_interfaces:
        config:
        - name: GigabitEthernet0/21
          access_groups:
        - afi: ipv4
          acls:
          - name: 110
            direction: in
          - name: 123
            direction: out
        - afi: ipv6
          acls:
          - name: test_v6
            direction: out
          - name: temp_v6
            direction: in
        - name: GigabitEthernet0/22
          access_groups:
          - afi: ipv4
            acls:
            - name: 100
              direction: in
        state: merged
